name: inception

services:
  mariadb:
    image: inception/mariadb
    build: ./mariadb
    restart: on-failure:10
    volumes:
      - wp-db:/var/lib/mysql
    env_file:
      - .env
  wordpress:
    image: inception/wordpress
    build: ./wordpress
    restart: on-failure:10
    depends_on:
      mariadb:
        condition: service_healthy
      redis: 
        condition: service_started
    volumes:
      - wp-files:/var/www
    env_file:
      - .env
  nginx:
    image: inception/nginx
    build: ./nginx
    restart: on-failure:10
    secrets:
      - site.key
      - site.crt
    depends_on:
      - wordpress
      - adminer
    volumes:
      - wp-files:/var/www
    ports:
      - 443:443
  redis:
    image: inception/redis
    build: ./bonus/redis
    restart: on-failure:10
  ftp:
    image: inception/ftp
    build: ./bonus/ftp
    restart: always
    secrets:
      - site.key
      - site.crt
    depends_on:
      wordpress:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - wp-files:/var/www
    ports:
      - 21:21
      - 10000-10010:10000-10010
  sftp:
    image: inception/sftp
    build: ./bonus/sftp
    restart: on-failure:10
    env_file:
      - .env
    volumes:
      - wp-files:/var/www
      - wp-db:/var/lib/mysql
    ports:
      - 22:22
  adminer:
    image: inception/adminer
    build: ./bonus/adminer
    restart: on-failure:10
  peufo:
    image: inception/peufo
    build: ./bonus/peufo
    restart: on-failure:10

networks:
  default:
    name: inception

volumes:
  wp-db:
    driver: local
    driver_opts:
      device: /home/jvoisard/data/db
      type: none
      o: bind
  wp-files:
    driver: local
    driver_opts:
      device: /home/jvoisard/data/files
      type: none
      o: bind

secrets:
  site.key:
    file: ../secrets/site.key
  site.crt:
    file: ../secrets/site.crt
