services:
  db:
    image: inception/mariadb
    build: ./srcs/mariadb
    volumes:
      - wp-db:/var/lib/mysql
    env_file:
      - .env
    
  # wp:
  #   image: inception/wordpress
  #   build: ./srcs/wordpress
  # web:
  #   image: inception/nginx
  #   build: ./srcs/nginx
  #   ports:
  #     - 8080:80

networks:
  default:
    name: inception

volumes:
  wp-db:
    # driver: local
    # driver_opts:
    #   device: ~/data/db
    #   type: none
    #   o: bind
  wp-files:
    # driver: local
    # driver_opts:
    #   device: ~/data/files
    #   type: none
    #   o: bind