name: inception

services:
  mariadb:
    image: inception/mariadb
    build: ./mariadb
    volumes:
      - wp-db:/var/lib/mysql
    env_file:
      - .env
    restart: always
  wordpress:
    image: inception/wordpress
    build: ./wordpress
    depends_on:
      mariadb:
        condition: service_healthy
      redis: 
        condition: service_started
    volumes:
      - wp-files:/var/www
    env_file:
      - .env
    restart: always
  web:
    image: inception/nginx
    build: ./nginx
    secrets:
      - site.key
      - site.crt
    depends_on:
      - wordpress
      - adminer
    volumes:
      - wp-files:/var/www
    ports:
      - 443:443
  redis:
    image: inception/redis
    build: ./bonus/redis
  ftp:
    image: inception/ftp
    build: ./bonus/ftp
    secrets:
      - site.key
      - site.crt
    depends_on:
      wordpress:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - wp-files:/var/www
    ports:
      - 21:21
  adminer:
    image: inception/adminer
    build: ./bonus/adminer

networks:
  default:
    name: inception

volumes:
  wp-db:
    # driver: local
    # driver_opts:
    #   device: ~/data/db
    #   type: none
    #   o: bind
  wp-files:
    # driver: local
    # driver_opts:
    #   device: ~/data/files
    #   type: none
    #   o: bind

secrets:
  site.key:
    file: ../secrets/site.key
  site.crt:
    file: ../secrets/site.crt
