services:
  mariadb:
    image: inception/mariadb
    build: ./srcs/mariadb
    volumes:
      - wp-db:/var/lib/mysql
    env_file:
      - .env
    restart: always
  wordpress:
    image: inception/wordpress
    build: ./srcs/wordpress
    depends_on:
      - mariadb
    volumes:
      - wp-files:/var/www
    env_file:
      - .env
    restart: always
  web:
    image: inception/nginx
    build: ./srcs/nginx
    depends_on:
      - mariadb
    ports:
      - 8080:80

networks:
  default:
    name: inception

volumes:
  wp-db:
    driver: local
    driver_opts:
      # device: ~/data/db
      device: /data/db
      type: none
      o: bind
  wp-files:
    driver: local
    driver_opts:
      # device: ~/data/files
      device: /data/files
      type: none
      o: bind